# Generated by Django 4.1.7 on 2023-04-12 03:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="groupchatmember",
            name="group_chat",
        ),
        migrations.RemoveField(
            model_name="groupchatmember",
            name="user",
        ),
        migrations.RemoveField(
            model_name="groupchatmessage",
            name="group_chat",
        ),
        migrations.RemoveField(
            model_name="groupchatmessage",
            name="sender",
        ),
        migrations.RemoveField(
            model_name="message",
            name="receiver",
        ),
        migrations.RemoveField(
            model_name="message",
            name="sender",
        ),
        migrations.DeleteModel(
            name="GroupChat",
        ),
        migrations.DeleteModel(
            name="GroupChatMember",
        ),
        migrations.DeleteModel(
            name="GroupChatMessage",
        ),
        migrations.DeleteModel(
            name="Message",
        ),
    ]
