# Generated by Django 4.2 on 2023-05-10 06:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("private", "Private"),
                    ("private_only", "Private Only"),
                ],
                default="public",
                max_length=20,
            ),
        ),
    ]
