# Generated by Django 4.2 on 2023-06-01 04:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0003_rename_like_post_likes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="comment",
            new_name="comments",
        ),
    ]
