# Generated by Django 4.1.7 on 2023-04-11 04:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("friends", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="friend",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AlterUniqueTogether(
            name="friend",
            unique_together={("user", "friend")},
        ),
    ]
