# Generated by Django 4.1.7 on 2023-04-11 06:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("friends", "0002_alter_friend_options_alter_friend_unique_together"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Friend",
        ),
    ]
