# Generated by Django 4.2.2 on 2023-10-03 16:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="birth_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="sex",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(
                max_length=500,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_password",
                        message="Password must be at least 8 characters long, contain at least one uppercase letter, one lower case letter, one number and one special character",
                        regex="^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)[a-zA-Z\\d](?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{8,}$",
                    )
                ],
                verbose_name="Password",
            ),
        ),
    ]
