# Generated by Django 4.1.7 on 2023-04-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_created_at_user_phone_number_user_tc_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["username", "email", "phone_number"],
                name="users_user_usernam_cab68a_idx",
            ),
        ),
    ]
