# Generated by Django 4.1.7 on 2023-04-05 15:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_user_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(
                max_length=100,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_password",
                        message="Password must be 8 characters long, contain at least one uppercase letter, one lowercase letter and one number",
                        regex="^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)[a-zA-Z\\d]{8,}$",
                    )
                ],
                verbose_name="Password",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                max_length=100,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_user_name",
                        message="User Name must be Alphanumeric",
                        regex="^[a-zA-Z0-9]*$",
                    )
                ],
                verbose_name="User Name",
            ),
        ),
    ]
