# Generated by Django 4.1.7 on 2023-04-05 15:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_user_password_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(
                max_length=500,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_password",
                        message="Password must be 8 characters long, contain at least one uppercase letter, one lowercase letter and one number",
                        regex="^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)[a-zA-Z\\d]{8,}$",
                    )
                ],
                verbose_name="Password",
            ),
        ),
    ]
