# Generated by Django 4.1.7 on 2023-04-06 03:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(
                max_length=500,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_password",
                        message="Password must be at least 8 characters long and contain at least one uppercase letter, one lowercase letter, one number and one special character",
                        regex="^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[-+_!@#$%^&*.,?])[A-Za-z\\d-+_!@#$%^&*.,?]{8,}$",
                    )
                ],
                verbose_name="Password",
            ),
        ),
    ]
