# Generated by Django 4.1.7 on 2023-04-06 04:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_alter_user_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(
                max_length=500,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_password",
                        message="Password must be at least 8 characters long, contain at least one uppercase letter, one lowercase letter, one number and one special character",
                        regex="^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)[a-zA-Z\\d](?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{8,}$",
                    )
                ],
                verbose_name="Password",
            ),
        ),
    ]
